apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: amp-email-platform
  labels:
    app: amp-email-platform
    environment: production
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: amp-email-service-account@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: amp-email-api
        image: REGION-docker.pkg.dev/PROJECT_ID/amp-email/platform:latest
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: API_VERSION
          value: v1
        - name: GCP_PROJECT_ID
          value: PROJECT_ID
        - name: R2_BUCKET_NAME
          value: amp-email-templates-production
        - name: R2_ENDPOINT
          value: https://ACCOUNT_ID.r2.cloudflarestorage.com
        - name: CDN_BASE_URL
          value: https://cdn.amp-platform.com
        - name: REDIS_HOST
          value: REDIS_HOST
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_USERNAME
          value: default
        - name: REPLICATE_MODEL
          value: meta/llama-2-70b-chat:latest
        - name: PRODUCT_SCRAPER_BASE_URL
          value: https://product-scraper-217130114839.us-east1.run.app
        - name: RATE_LIMIT_ENABLED
          value: 'true'
        - name: LOG_LEVEL
          value: info
        - name: AI_GENERATION_COST_USD
          value: '0.0024'
        - name: SCRAPING_COST_USD
          value: '0.0003'
        - name: CDN_COST_USD
          value: '0.0010'
        - name: SUPABASE_URL
          value: https://oeztikupnlchucnhhhnf.supabase.co
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: DIRECT_URL
          valueFrom:
            secretKeyRef:
              name: direct-url
              key: latest
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: latest
        - name: REPLICATE_API_KEY
          valueFrom:
            secretKeyRef:
              name: replicate-api-key
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-anon-key
              key: latest
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-service-role-key
              key: latest
        - name: R2_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: r2-account-id
              key: latest
        - name: R2_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: r2-access-key-id
              key: latest
        - name: R2_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: r2-secret-access-key
              key: latest
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
